name: Trigger Jenkins Job on File Changes
on: 
  push:
    branches:
      - main
      - staging

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Configure Git
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40.2.0

      - name: Trigger Jenkins job for orders
        if: contains(steps.changed-files.outputs.all_changed_files, 'orders/')
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="PRODUCTION"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            ENVIRONMENT="STAGING"
          fi
          curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_KEY }} \
            "${{ secrets.JENKINS_HOST }}/job/DEPLOYMENTS/job/$ENVIRONMENT/job/ORDERS/build?token=${JENKINS_TOKEN_NAME}"

      - name: Trigger Jenkins job for users
        if: contains(steps.changed-files.outputs.all_changed_files, 'users/')
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="PRODUCTION"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            ENVIRONMENT="STAGING"
          fi
          curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_KEY }} \
            "${{ secrets.JENKINS_HOST }}/job/DEPLOYMENTS/job/$ENVIRONMENT/job/USERS/build?token=${JENKINS_TOKEN_NAME}"


